# Generated by Django 5.0.1 on 2024-01-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchant_id', models.AutoField(primary_key=True, serialize=False)),
                ('merchant_en_name', models.CharField(max_length=255)),
                ('merchant_ar_name', models.CharField(max_length=255)),
            ],
        ),
    ]
