# Generated by Django 5.0.1 on 2024-01-17 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('is_master', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 0.')])),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.city')),
            ],
        ),
    ]
