# Generated by Django 5.0.1 on 2024-01-15 17:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_en_name', models.CharField(max_length=255)),
                ('category_ar_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ColorCategory',
            fields=[
                ('color_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_category_en_name', models.CharField(max_length=255)),
                ('color_category_ar_name', models.CharField(max_length=255)),
                ('color_category_hex', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SizeCategory',
            fields=[
                ('size_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_category_en_name', models.CharField(max_length=255)),
                ('size_category_ar_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=255)),
                ('color_hex', models.CharField(max_length=50)),
                ('color_order', models.IntegerField(default=0)),
                ('color_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.colorcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_en_name', models.CharField(max_length=255)),
                ('product_ar_name', models.CharField(max_length=255)),
                ('product_en_description', models.CharField(max_length=1000)),
                ('product_ar_description', models.CharField(max_length=1000)),
                ('has_sizes', models.BooleanField(default=False)),
                ('has_colors', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('product_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='product_photos/')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('product_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 0.'), django.core.validators.MaxValueValidator(5, message='Value must be less than or equal to 5.')])),
                ('review_text', models.TextField(max_length=1000)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('product_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_name', models.CharField(max_length=100)),
                ('size_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sizecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('product_stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 0.')])),
                ('color_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.colors')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('size_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sizes')),
            ],
        ),
    ]
