# Generated by Django 5.0.1 on 2024-01-15 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='merchant_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant'),
            preserve_default=False,
        ),
    ]
