# Generated by Django 5.0.1 on 2024-01-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_merchant_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
    ]
